platform :ios, '8.0'
target 'FoodPin' do
# Uncomment this line if you're using Swift or would like to use dynamic frameworks
# Pods for FoodPin
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'FBMemoryProfiler'
# use_frameworks!
# pod 'ReactiveCocoa'
end
